query getPokemon($id: String, $name: String){
  pokemon(id: $id,name:$name) {
    id
    number
    classification
    name
    types
    resistant
    weaknesses
    image
    weight {
      minimum
      maximum
    }
    height {
      minimum
      maximum
    }
  }
}