name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - uses: actions/cache@v3
      id: node_modules_cache_id
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: install
      if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
      run: npm ci
    - name: build
      run: npm run build
    - name: export
      run: npm run export
    - name: add nojekyll
      run: touch ./out/.nojekyll
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out